server:
  port: 8083

spring:
  application:
    name: auction-service

  datasource:
    url: jdbc:mysql://localhost:3306/openbox
    username: openbox_user
    password: openbox_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret-key: b3BlbmJveC12ZXJ5LXNlY3JldC1rZXktcGxlYXNlLXVzZS10aGlzISE=
  expire-length: 3600000